/**:
  ros__parameters:
    # RPLiDAR Configuration
    serial_port: /dev/ttyUSB0
    serial_baudrate: 115200
    frame_id: laser
    inverted: false
    angle_compensate: true
    min_range: 0.15
    max_range: 8.0
